In [17]:
import torch
import torch.nn.functional as F

import numpy as np

In [2]:
tensor=torch.tensor([[1,2,3],
                    [4,5,6],
                    [7, 8,9]])
tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
unf=tensor.unfold(1, 1,1)
print(tensor.size())
print(unf.size())
unf

torch.Size([3, 3])
torch.Size([3, 3, 1])


tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])

In [13]:
unf=tensor.unfold(0, 1,1)
print(tensor.size())
print(unf.size())
unf

torch.Size([3, 3])
torch.Size([3, 3, 1])


tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])

In [10]:
unf=tensor.unfold(1, 1,2)
print(tensor.size())
print(unf.size())
unf

torch.Size([3, 3])
torch.Size([3, 2, 1])


tensor([[[1],
         [3]],

        [[4],
         [6]],

        [[7],
         [9]]])

In [5]:
tensor.unfold(1,2,1)

tensor([[[1, 2],
         [2, 3]],

        [[4, 5],
         [5, 6]],

        [[7, 8],
         [8, 9]]])

In [16]:
tensor.unfold(1,2,2)

tensor([[[1, 2]],

        [[4, 5]],

        [[7, 8]]])

## Functional unfold

In [19]:
#load data
tensor=torch.tensor(np.load('data/tenors.npy'))

In [20]:
tensor.size()

torch.Size([9, 1, 400, 257])

In [21]:
context_size=5
input_dim=257
dilation=1

x = F.unfold(
            tensor,
            (context_size, input_dim),
            stride=(1, input_dim),
            dilation=(dilation, 1)
        )

In [23]:
x.size()

torch.Size([9, 1285, 396])

In [26]:
x = F.unfold(
            tensor,
            (context_size, input_dim),
            stride=(1, input_dim),
            dilation=1
        )
x.size()

torch.Size([9, 1285, 396])

In [27]:
context_size*input_dim

1285

In [36]:
cnt=0
for i in range(396):
    if i+3<=396:
        cnt+=1

In [37]:
cnt

394

In [35]:
i

395