In [25]:
import scipy.linalg 
import scipy as sp
import numpy as np
import pandas as pd

Source: https://www.analyticsvidhya.com/blog/2017/05/comprehensive-guide-to-linear-algebra/

## Terms

Rank of a matrix – Rank of a matrix is equal to the maximum number of linearly independent row vectors in a matrix.

## Matrix transpose

In [8]:
#create a 3*3 matrix
a= np.arange(21,30).reshape(3,3)

In [9]:
a

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [10]:
a.T

array([[21, 24, 27],
       [22, 25, 28],
       [23, 26, 29]])

## Matrix addition

In [11]:
b=np.arange(11,20).reshape(3,3)
b

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [12]:
a+b

array([[32, 34, 36],
       [38, 40, 42],
       [44, 46, 48]])

## Matrix multiplication

In [17]:
a=np.arange(21,30).reshape(3,3)
b=np.arange(31,40).reshape(3,3)
print(a);print(b)

[[21 22 23]
 [24 25 26]
 [27 28 29]]
[[31 32 33]
 [34 35 36]
 [37 38 39]]


In [14]:
#pder that python 3.6 use np.dot(a,b)
a@b

array([[2250, 2316, 2382],
       [2556, 2631, 2706],
       [2862, 2946, 3030]])

#### Matrix multiplication is associative provided the given matrices are compatible for multiplication i.e. ABC =  (AB)C = A(BC)

In [19]:
A=np.arange(21,30).reshape(3,3)
B=np.arange(31,40).reshape(3,3)
C=np.arange(41,50).reshape(3,3)

temp1=(A@B)@(C)
temp1

array([[306108, 313056, 320004],
       [347742, 355635, 363528],
       [389376, 398214, 407052]])

In [20]:
temp2=A@((B@(C)))
temp2

array([[306108, 313056, 320004],
       [347742, 355635, 363528],
       [389376, 398214, 407052]])

## LU decomposition

Using Gaussian Elimination. Example:

A =
 \begin{pmatrix}
  1 & -2 & -2 & -3 \\
  3 & -9 & 0 & -9 \\
  -1 & 2 & 4 & 7  \\
  -3 & -6 & 26 & 2
 \end{pmatrix}

Answer:

$$ LU = \begin{bmatrix} 1 & 0 & 0 & 0\\ 3 & 1 & 0 & 0 \\ -1 & 0 & 1 & 0 \\ -3 & 4 & -2 & 1\end{bmatrix} \cdot \begin{bmatrix} 1 & -2 & -2 & -3 \\ 0 & -3 & 6 & 0 \\ 0 & 0 & 2 & 4 \\ 0 & 0 & 0 & 1 \end{bmatrix}$$

**Gaussian Elimination** transform a linear system into an upper triangular one by applying linear transformations on the left.  It is *triangular triangularization*.

$ L_{m-1} \dots L_2 L_1 A = U $

L is *unit lower-triangular*: all diagonal entries are 1

In [32]:
#custom function for LU factorization
def LU(A):
    U = np.copy(A)
    m, n = A.shape
    L = np.eye(n)
    for k in range(n-1):
        for j in range(k+1,n):
            L[j,k] = U[j,k]/U[k,k]
            U[j,k:n] -= L[j,k] * U[k,k:n]
    return L, U

In [39]:
A = np.array([[2,1,1,0],[4,3,3,1],[8,7,9,5],[6,7,9,8]]).astype(np.float)
A

array([[ 2.,  1.,  1.,  0.],
       [ 4.,  3.,  3.,  1.],
       [ 8.,  7.,  9.,  5.],
       [ 6.,  7.,  9.,  8.]])

In [40]:
L, U = LU(A)
#scipy version
P_sp, L_sp, U_sp = scipy.linalg.lu(A, check_finite)

In [41]:
L

array([[ 1.,  0.,  0.,  0.],
       [ 2.,  1.,  0.,  0.],
       [ 4.,  3.,  1.,  0.],
       [ 3.,  4.,  1.,  1.]])

In [42]:
U

array([[ 2.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.],
       [ 0.,  0.,  2.,  2.],
       [ 0.,  0.,  0.,  2.]])

In [45]:
np.allclose(A, L @ U)

True

sipy has a bit different solution, it uses permutation

In [43]:
L_sp

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.75      ,  1.        ,  0.        ,  0.        ],
       [ 0.5       , -0.28571429,  1.        ,  0.        ],
       [ 0.25      , -0.42857143,  0.33333333,  1.        ]])

In [44]:
U_sp

array([[ 8.        ,  7.        ,  9.        ,  5.        ],
       [ 0.        ,  1.75      ,  2.25      ,  4.25      ],
       [ 0.        ,  0.        , -0.85714286, -0.28571429],
       [ 0.        ,  0.        ,  0.        ,  0.66666667]])

In [47]:
P_sp #permuatation matrix, my version I dind't us that

array([[ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.]])

matrices U and U_sp are in row echelon form

In [48]:
np.allclose(A, P_sp @ L_sp @ U_sp)

True

The LU factorization is useful!

Solving Ax = b becomes LUx = b:
1. find A = LU
2. solve Ly = b
3. solve Ux = y

## Determinant

In [49]:
arr = np.arange(100,116).reshape(4,4)

In [50]:
np.linalg.det(arr)

-2.4233807008390354e-27

## Inverse of matrix

In [51]:
arr1 = np.arange(5,21).reshape(4,4)
np.linalg.inv(arr1)

array([[ -9.68516049e+14,   1.74332889e+15,  -5.81109629e+14,
         -1.93703210e+14],
       [  1.96931597e+15,  -3.24452876e+15,   5.81109629e+14,
          6.94103168e+14],
       [ -1.03308379e+15,   1.25907086e+15,   5.81109629e+14,
         -8.07096707e+14],
       [  3.22838683e+13,   2.42129012e+14,  -5.81109629e+14,
          3.06696749e+14]])

In [52]:
arr1

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

Inverse is used to calculate parameter vector by normal equation in linear equation.

## Application of inverse

To find the final parameter vector(θ) assuming our initial function is parameterised by θ and X , all you have to do is to find the inverse of (XT X) which can be accomplished very easily by using code as shown below.

First of all, let me make the Linear Regression formulation easier for you to comprehend.

f θ (X)= θT X, where θ is the parameter we wish to calculate and X is the column vector of features or independent variables.

In [53]:
df=pd.read_csv('data/baseball.csv')

In [54]:
df.head()

Team League  Year   RS   RA   W    OBP    SLG     BA  Playoffs  RankSeason  \
0  ARI     NL  2012  734  688  81  0.328  0.418  0.259         0         NaN   
1  ATL     NL  2012  700  600  94  0.320  0.389  0.247         1         4.0   
2  BAL     AL  2012  712  705  93  0.311  0.417  0.247         1         5.0   
3  BOS     AL  2012  734  806  69  0.315  0.415  0.260         0         NaN   
4  CHC     NL  2012  613  759  61  0.302  0.378  0.240         0         NaN   

   RankPlayoffs    G   OOBP   OSLG  
0           NaN  162  0.317  0.415  
1           5.0  162  0.306  0.378  
2           4.0  162  0.315  0.403  
3           NaN  162  0.331  0.428  
4           NaN  162  0.335  0.424

In [56]:
#use just subset
Df1 = df.head(14)

X = Df1[["RS", "RA", "W", "OBP",'SLG','BA']]
Y=Df1['OOBP']

Recall that we want to find $\hat{x}$ that minimizes: 
$$ \big\vert\big\vert Ax - b \big\vert\big\vert_2$$

Another way to think about this is that we are interested in where vector $b$ is closest to the subspace spanned by $A$ (called the *range of* $A$).  This is the projection of $b$ onto $A$.  Since $b - A\hat{x}$ must be perpendicular to the subspace spanned by $A$, we see that

$$A^T (b - A\hat{x}) = 0 $$

(we are using $A^T$ because we want to multiply each column of $A$ by $b - A\hat{x}$

This leads us to the *normal equations*:
$$ x = (A^TA)^{-1}A^T b $$

In [63]:
#Converting X to matrix
X = np.asmatrix(X)
#taking transpose of X and assigning it to x
x= X.T
#finding multiplication
T= x@X
#inverse of T - provided it is invertible otherwise we use pseudoinverse
inv=np.linalg.inv(T)
#calculating θ
theta=(inv@X.T).dot(Y)

In [64]:
theta

matrix([[ -2.59951184e-04,   1.53102522e-04,  -6.98603725e-05,
           6.57605847e-01,   4.00767706e-01,   1.07696279e-01]])

## Eigenvectors and eigenvalues

In [65]:
arr = np.arange(1,10).reshape(3,3)
np.linalg.eig(arr)

(array([  1.61168440e+01,  -1.11684397e+00,  -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))