In [1]:
import numpy as np

In [10]:
A = np.array([[60, 91, 26], [60, 3, 75], [45, 90, 31]], dtype='float')
b = np.array([1, 0, 0])

Ab = np.hstack([A, b.reshape(-1, 1)])
Ab

array([[60., 91., 26.,  1.],
       [60.,  3., 75.,  0.],
       [45., 90., 31.,  0.]])

In [11]:
n = len(b)

for i in range(n):
    a = Ab[i]

    for j in range(i + 1, n):
        b = Ab[j]
        m = a[i] / b[i]
        Ab[j] = a - m * b

for i in range(n - 1, -1, -1):
    Ab[i] = Ab[i] / Ab[i, i]
    a = Ab[i]

    for j in range(i - 1, -1, -1):
        b = Ab[j]
        m = a[i] / b[i]
        Ab[j] = a - m * b

In [12]:
x = Ab[:, 3]
x

array([ 0.05339911, -0.01215257, -0.04223318])

In [14]:
Ab.round(3)

array([[ 1.   , -0.   , -0.   ,  0.053],
       [ 0.   ,  1.   ,  0.   , -0.012],
       [-0.   , -0.   ,  1.   , -0.042]])